// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAB7FD3BmDHo33H7BGF3J9FRL00ngOaNbQ',
    appId: '1:1782012780:android:be3fc14d630a552bed7149',
    messagingSenderId: '1782012780',
    projectId: 'chatter-io-355e4',
    storageBucket: 'chatter-io-355e4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClbA8DYMKetavgEWYsYvm8V7g1vab5Xj4',
    appId: '1:1782012780:ios:01714c62de61cf5fed7149',
    messagingSenderId: '1782012780',
    projectId: 'chatter-io-355e4',
    storageBucket: 'chatter-io-355e4.appspot.com',
    androidClientId: '1782012780-504n2bggp0vej11usl9i21r705i759cf.apps.googleusercontent.com',
    iosClientId: '1782012780-5iltl7rrmft4u4oieupsfd6t4hoq3a01.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatterIo',
  );
}
